In [1]:
import torch
import torch.nn as nn

In [12]:
class Module(nn.Module):
    
    def __init__(self,num_features):
        
        super().__init__()   # calling constructor of nn.Module                               #
        self.linear=nn.Linear(num_features,1) # this takes no.of feat and no.of output        #  # --- we create layers in this region
        self.sigmoid=nn.Sigmoid()                                                             #

    def forward(self,features):
        
        out=self.linear(features) # here z=wx+b is calculated                                 #  
        out=self.sigmoid(out) # z is passed to sigmoid fun                                    #  # ---- here we use them
        return out                                                                            #
        
        
        

In [7]:
# create dataset
features=torch.rand(10,5)

#create model
model=Module(features.shape[1])

#call model forward pass
model(features) # can also do model.forward(features)

tensor([[0.4942],
        [0.4737],
        [0.4734],
        [0.4468],
        [0.5105],
        [0.5273],
        [0.5132],
        [0.4933],
        [0.5096],
        [0.5064]], grad_fn=<SigmoidBackward0>)

In [10]:
model.linear.weight

Parameter containing:
tensor([[-0.1965,  0.0633,  0.1349, -0.0324,  0.3353]], requires_grad=True)

In [11]:
model.linear.bias

Parameter containing:
tensor([-0.1957], requires_grad=True)

In [13]:
!pip install torchinfo

In [14]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Module                                   [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00