In [2]:
import torch
print(torch.__version__)

2.9.1+cpu


In [3]:
import pandas as pd
import numpy as np

In [4]:
data=pd.read_csv("/Users/koour/Downloads/archive (1)/framingham.csv")

In [5]:
data.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [6]:
data.dropna(inplace=True)

In [7]:
data.shape

(3656, 16)

In [8]:
dataframe=data.iloc[:300]

In [9]:
dataframe.shape 
#changed shape so that it will be easy

(300, 16)

In [10]:
x=dataframe.drop("TenYearCHD",axis=1)
x

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0       1   39        4.0              0         0.0     0.0                0   
1       0   46        2.0              0         0.0     0.0                0   
2       1   48        1.0              1        20.0     0.0                0   
3       0   61        3.0              1        30.0     0.0                0   
4       0   46        3.0              1        23.0     0.0                0   
..    ...  ...        ...            ...         ...     ...              ...   
340     0   58        1.0              0         0.0     0.0                0   
341     0   42        1.0              1        20.0     0.0                0   
342     0   41        4.0              1        15.0     0.0                0   
344     0   63        1.0              1        20.0     0.0                0   
346     0   53        2.0              0         0.0     1.0                0   

     prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  
0               0         0    195.0  106.0   70.0  26.97       80.0     77.0  
1               0         0    250.0  121.0   81.0  28.73       95.0     76.0  
2               0         0    245.0  127.5   80.0  25.34       75.0     70.0  
3               1         0    225.0  150.0   95.0  28.58       65.0    103.0  
4               0         0    285.0  130.0   84.0  23.10       85.0     85.0  
..            ...       ...      ...    ...    ...    ...        ...      ...  
340             1         0    200.0  158.0  101.0  23.06       85.0     77.0  
341             0         0    237.0  105.0   75.0  23.85       70.0     87.0  
342             0         0    207.0  111.0   60.0  18.48       60.0     76.0  
344             0         0    238.0  136.0   66.0  20.20       60.0     92.0  
346             1         0    250.0  144.0   98.0  28.78       90.0     78.0  

[300 rows x 15 columns]

In [11]:
y=dataframe[["TenYearCHD"]]
y

TenYearCHD
0             0
1             0
2             0
3             1
4             0
..          ...
340           1
341           0
342           0
344           1
346           0

[300 rows x 1 columns]

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [13]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [14]:
y_train=np.array(y_train)
y_test=np.array(y_test)

In [15]:
s=StandardScaler()
X_train=s.fit_transform(X_train)
X_test=s.transform(X_test)

In [16]:
X_train

array([[-0.80842025,  0.77579155,  0.05468347, ..., -0.77898492,
         0.09074279, -0.38274005],
       [ 1.23698039, -0.02506068, -0.90227721, ...,  1.41442271,
        -0.0742441 ,  1.62431142],
       [ 1.23698039, -1.05472784,  0.05468347, ...,  1.04737174,
         0.75069033, -0.80282059],
       ...,
       [-0.80842025, -1.28354277,  1.96860482, ...,  0.05522184,
        -0.65169819,  0.22404295],
       [-0.80842025, -0.36828307,  1.01164414, ..., -0.38079023,
         0.33822311,  0.50409665],
       [ 1.23698039,  1.11901394, -0.90227721, ...,  0.11750928,
        -1.72411295, -0.33606443]])

In [17]:
#converting  numpy arrays to tenors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [18]:
X_train_tensor.shape
# it has 15 features,so our neural network will have 15 weights

torch.Size([210, 15])

In [19]:
X_train_tensor.dtype

torch.float64

In [20]:
y_train_tensor.shape

torch.Size([210, 1])

In [21]:
from torch.utils.data import Dataset,DataLoader

In [22]:
# Making Customdataset using Dataset
class Customdataset(Dataset):
    
    def __init__(self,features,lables):
        self.features=features
        self.lables=lables
        
    def __len__(self):
        return self.features.shape[0]
        
    def __getitem__(self,index):
        return self.features[index],self.lables[index]

In [23]:
train_dataset=Customdataset(X_train_tensor,y_train_tensor)  # dataset obj for training
test_dataset=Customdataset(X_test_tensor,y_test_tensor)      # dataset obj for testing

In [26]:
train_dataset[2]

(tensor([ 1.2370, -1.0547,  0.0547,  1.0488,  2.7216, -0.1715, -0.0692,  1.4936,
         -0.1990,  0.8912,  0.8599,  0.6427,  1.0474,  0.7507, -0.8028],
        dtype=torch.float64),
 tensor([0]))

In [24]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True) # here we pass obj of  train dataset 
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)   # here we pass obj of  test dataset 
# we cannot access using index here,we have to use for loop to access feat and lables

In [31]:
## defining model
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [32]:
#parameters
learning_rate=0.1
epochs=25

In [33]:
# create model

model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

In [37]:
# training pipeline

# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:
      
      batch_features = batch_features.float()
      batch_labels = batch_labels.float()


    # forward pass
      y_pred = model(batch_features)

    # loss calculate
      loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
      optimizer.zero_grad()

    # backward pass
      loss.backward()

    # parameters update
      optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 0.7518607974052429
Epoch: 2, Loss: 0.5737974643707275
Epoch: 3, Loss: 0.5585528016090393
Epoch: 4, Loss: 0.6131396293640137
Epoch: 5, Loss: 0.5731516480445862
Epoch: 6, Loss: 0.49219003319740295
Epoch: 7, Loss: 0.37306368350982666
Epoch: 8, Loss: 0.48276981711387634
Epoch: 9, Loss: 0.4041379690170288
Epoch: 10, Loss: 0.5350000262260437
Epoch: 11, Loss: 0.5302306413650513
Epoch: 12, Loss: 0.33447474241256714
Epoch: 13, Loss: 0.3836197257041931
Epoch: 14, Loss: 0.3171032667160034
Epoch: 15, Loss: 0.4049721956253052
Epoch: 16, Loss: 0.305439293384552
Epoch: 17, Loss: 0.501013457775116
Epoch: 18, Loss: 0.4286295175552368
Epoch: 19, Loss: 0.43500423431396484
Epoch: 20, Loss: 0.37123167514801025
Epoch: 21, Loss: 0.26697614789009094
Epoch: 22, Loss: 0.39688217639923096
Epoch: 23, Loss: 0.3693559467792511
Epoch: 24, Loss: 0.5701843500137329
Epoch: 25, Loss: 0.3705850839614868


In [41]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        batch_features = batch_features.float()
        batch_labels = batch_labels.float()
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.8289
