In [1]:
import torch
print(torch.__version__)

2.9.1+cpu


In [3]:
import pandas as pd
import numpy as np

In [4]:
data=pd.read_csv("/Users/koour/Downloads/archive (1)/framingham.csv")

In [5]:
data.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [8]:
data.dropna(inplace=True)

In [11]:
data.shape

(3656, 16)

In [12]:
dataframe=data.iloc[:300]

In [13]:
dataframe.shape 
#changed shape so that it will be easy

(300, 16)

In [14]:
x=dataframe.drop("TenYearCHD",axis=1)
x

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0       1   39        4.0              0         0.0     0.0                0   
1       0   46        2.0              0         0.0     0.0                0   
2       1   48        1.0              1        20.0     0.0                0   
3       0   61        3.0              1        30.0     0.0                0   
4       0   46        3.0              1        23.0     0.0                0   
..    ...  ...        ...            ...         ...     ...              ...   
340     0   58        1.0              0         0.0     0.0                0   
341     0   42        1.0              1        20.0     0.0                0   
342     0   41        4.0              1        15.0     0.0                0   
344     0   63        1.0              1        20.0     0.0                0   
346     0   53        2.0              0         0.0     1.0                0   

     prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  
0               0         0    195.0  106.0   70.0  26.97       80.0     77.0  
1               0         0    250.0  121.0   81.0  28.73       95.0     76.0  
2               0         0    245.0  127.5   80.0  25.34       75.0     70.0  
3               1         0    225.0  150.0   95.0  28.58       65.0    103.0  
4               0         0    285.0  130.0   84.0  23.10       85.0     85.0  
..            ...       ...      ...    ...    ...    ...        ...      ...  
340             1         0    200.0  158.0  101.0  23.06       85.0     77.0  
341             0         0    237.0  105.0   75.0  23.85       70.0     87.0  
342             0         0    207.0  111.0   60.0  18.48       60.0     76.0  
344             0         0    238.0  136.0   66.0  20.20       60.0     92.0  
346             1         0    250.0  144.0   98.0  28.78       90.0     78.0  

[300 rows x 15 columns]

In [16]:
y=dataframe[["TenYearCHD"]]
y

TenYearCHD
0             0
1             0
2             0
3             1
4             0
..          ...
340           1
341           0
342           0
344           1
346           0

[300 rows x 1 columns]

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [18]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [25]:
y_train=np.array(y_train)
y_test=np.array(y_test)

In [19]:
s=StandardScaler()
X_train=s.fit_transform(X_train)
X_test=s.transform(X_test)

In [20]:
X_train

array([[-0.80842025,  0.77579155,  0.05468347, ..., -0.77898492,
         0.09074279, -0.38274005],
       [ 1.23698039, -0.02506068, -0.90227721, ...,  1.41442271,
        -0.0742441 ,  1.62431142],
       [ 1.23698039, -1.05472784,  0.05468347, ...,  1.04737174,
         0.75069033, -0.80282059],
       ...,
       [-0.80842025, -1.28354277,  1.96860482, ...,  0.05522184,
        -0.65169819,  0.22404295],
       [-0.80842025, -0.36828307,  1.01164414, ..., -0.38079023,
         0.33822311,  0.50409665],
       [ 1.23698039,  1.11901394, -0.90227721, ...,  0.11750928,
        -1.72411295, -0.33606443]])

In [29]:
#converting  numpy arrays to tenors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [36]:
X_train_tensor.shape
# it has 15 features,so our neural network will have 15 weights

torch.Size([210, 15])

In [37]:
X_train_tensor.dtype

torch.float64

In [33]:
y_train_tensor.shape

torch.Size([210, 1])

In [66]:
## defining model
class MyNN:
    def __init__(self,X):

        self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)#here we need this for differentiation so requires is true
        self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)#here we need this for differentiation so requires is true
    
    def forward_pass(self,X):
        z=torch.matmul(X,self.weights)+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    #loss calculate
    def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

    
    #backward pass
    #parameters update

In [72]:
#parameters
learning_rate=0.1
epochs=25

In [69]:
# create model
model=MyNN(X_train_tensor)
model.weights

tensor([[0.2287],
        [0.8780],
        [0.3218],
        [0.5688],
        [0.7034],
        [0.8105],
        [0.5819],
        [0.7983],
        [0.4976],
        [0.5956],
        [0.0273],
        [0.6731],
        [0.0982],
        [0.5011],
        [0.0493]], dtype=torch.float64, requires_grad=True)

In [47]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [73]:
# training pipeline
model=MyNN(X_train_tensor)
#forward pass
for epoch in range(epochs):
    y_pred=model.forward_pass(X_train_tensor)
    # print(y_pred)
    # print(y_pred.shape)
    
# loss calculation
    loss=model.loss_function(y_pred,y_train_tensor)
    
    
# backward pass
    loss.backward()

# parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

# zero gradients---for every epoch they are started with o
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    
#loss in every epoch
    print(f'epoch:{epoch+1} ,loss:{loss.item()}')


epoch:1 ,loss:1.0352394774482514
epoch:2 ,loss:1.0146414615899524
epoch:3 ,loss:0.9945513940019899
epoch:4 ,loss:0.9749715588886014
epoch:5 ,loss:0.9559032574513684
epoch:6 ,loss:0.9373467930509369
epoch:7 ,loss:0.9193014676976805
epoch:8 ,loss:0.9017655889749658
epoch:9 ,loss:0.8847364862872975
epoch:10 ,loss:0.868210535259577
epoch:11 ,loss:0.8521831891258561
epoch:12 ,loss:0.8366490160370236
epoch:13 ,loss:0.8216017413526324
epoch:14 ,loss:0.8070342941322985
epoch:15 ,loss:0.7929388571840246
epoch:16 ,loss:0.7793069201488372
epoch:17 ,loss:0.7661293351972612
epoch:18 ,loss:0.7533963749778816
epoch:19 ,loss:0.7410977925040407
epoch:20 ,loss:0.7292228826891181
epoch:21 ,loss:0.7177605452530751
epoch:22 ,loss:0.7066993487188099
epoch:23 ,loss:0.6960275952010484
epoch:24 ,loss:0.6857333856527578
epoch:25 ,loss:0.6758046851793283


In [74]:
model.weights

tensor([[ 0.1907],
        [ 0.4899],
        [ 0.5149],
        [ 0.3310],
        [ 0.3240],
        [ 0.5065],
        [ 0.3039],
        [ 0.1375],
        [-0.0483],
        [ 0.6294],
        [ 0.6022],
        [ 0.2378],
        [ 0.3101],
        [-0.1213],
        [ 0.2826]], dtype=torch.float64, requires_grad=True)

In [75]:
model.bias

tensor([-0.6021], dtype=torch.float64, requires_grad=True)

In [77]:
# evaluation
with torch.no_grad():
  y_pred = model.forward_pass(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.8222222328186035
